<?php

require_once 'Model/Core/Url.php';
$url = new Model_Core_Url();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Category</title>
   
</head>

<body>
    <?php require_once 'View/html/header.phtml' ?>
    <div class="content-main">
        <form action="<?php echo ($url->getUrl('category','save'));?>" method="post">
            <table>
                <tr>
                    <td>
                        <h1>Add Category</h1>
                    </td>
                    <td class="sub-head">
                        <a href="<?php echo ($url->getUrl('category','grid'));?>">Cancel</a>
                        <button type="submit">Save</button>
                    </td>
                </tr>
            </table>
            <table border="2px" style="border-collapse: collapse">
                <tr>
                    <td>Parent: </td>
                    <td><select name="category[parent_id]">
                        <option selected disable>-Choose Parent-</option>
                    </select>
                </td>
                <tr>
                    <td>Category_id: </td>
                    <td><input type="text" name="category[category_id]"></td>
                </tr>
                <tr>
                    <td>Name: </td>
                    <td><input type="text" name="category[name]"></td>
                </tr>
                <tr>
                    <td>Status: </td>
                    <td>
                        <select name="category[status]" id="">
                            <option value="1">Active</option>
                            <option value="2">Inactive</option>
                        </select>
                    </td>
                </tr>
             
                <tr>
                    <td>Description: </td>
                    <td>
                        <textarea name="category[description]"cols="30" rows="10"></textarea>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <?php require_once 'View/html/footer.phtml';?>
</body>

</html>