<?php
// $payments = $this->getPayments();
// require_once 'Model/Core/Url.php';
$url=Ccc::getModel('Core_Url');
$payments = $this->payments;

// require_once 'Model/Core/Table/Row.php';



?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
    <style>
        .content-main{
        border: 1px solid grey;
        min-height: 500px;
        height: auto;
        }
    </style>
</head>

<body>
    <?php require_once 'View/html/header.phtml'; ?>
    <div class="content-main">
        <div class="content">
            <h2>Manage Payment</h2>
            <a href="<?php echo ($url->getUrl('payment','add'));?>">Add Payment</a>
        </div>
        <div>
            <table border="1px">
                <tr>
                    <th style="width : 20px">Payment_Method_id</th>
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>inserted_at</th>
                    <th>updated_at</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                <?php
                //feching data to form from database
                foreach($payments as $row){

                ?>
                <tr>
                    <!-- all attributes of database -->
                    <td><?php echo $row->payment_id; ?></td>
                    <td><?php echo $row->name; ?></td>
                    <td><?php echo $row->amount; ?></td>
                    <td><?php echo $row->getStatusText(); ?></td>
                    <td><?php echo $row->inserted_at; ?></td>
                    <td><?php echo $row->updated_at; ?></td>
                    
                    <td><a href="<?php echo ($url->getUrl('payment','edit',['id'=>$row->payment_id]));?>">edit</a></td>
                    <td><a href="<?php echo ($url->getUrl('payment','delete',['id'=>$row->payment_id]));?>">delete</a></td>
                </tr>
                <?php
                }
                ?>
            </table>
        </div>
    </div>
    <?php require_once 'View/html/footer.phtml'; ?>
</body>

</html>